spring:
  application:
    name: csv-reader-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 500
        order_inserts: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

